### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by AlienJust** [DmitryNizhebovsky/ModernControlsForAvalonia#5]
Hi Dmirty! Thanks for sharing your work. Can you make nuget package please?

**Comment by AlienJust** [comment]
Or provide license information for the sources please. Then I can make unofficial package.

**Comment by DmitryNizhebovsky** [comment]
Hi!
Before publishing the nuget package, it would be best to change the target framework to netstandard2.0.
I'll add the license soon.
